[package]
name = "sdl_opengl"
version = "0.1.0"
authors = ["siabard"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
gl = "0.14"

[dependencies.sdl2]
version = "^0.33"
features = ["bundled", "static-link"]